version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto
    versions:
    - 3.5.6
    - 3.5.7
    - 3.5.8
    - 3.6.0
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: postgrex
    versions:
    - 0.15.8
